Add snap on river for all apps
Georiviere/Georiviere-admin pull request #24
Opened 2021-11-16 16:51 UTC by LePetitTim

* I added a way to snap with other geometries on Stream
* I added the widget on all geometries for all the apps

2021-11-24 14:12 UTC, numahell requested changes

2021-11-24 14:12 UTC, numahell commented on georiviere/river/fields.py
>              # geometry vertices
J'écrirais plutôt 

> Snapped paths list is used to modify the geometry vertices according to its type

2021-11-25 16:29 UTC, submarcos commented on georiviere/river/models.py
> +        return Point(*result[0], srid=self.geom.srid)
return self._meta.model.objects.filter(pk=self.pk).annotate(closest_point=Closest(point).closest_point ?

2021-11-25 16:30 UTC, submarcos commented on georiviere/river/models.py
> +        return Point(*result[0], srid=self.geom.srid)
avec : 
```python
class Closest(GeomOutputGeoFunc):
    geom_param_pos = (0, 1)
```

2021-11-25 16:33 UTC, submarcos commented on georiviere/river/models.py
> +        return Point(*result[0], srid=self.geom.srid)
- GeoFunc essaie tout seul d'utiliser la fonction postgis s'apellant ST_<NOMDELACLASSE>

- GeomOutputGeoFunc c'est GeoFunc avec le output_field en GeometryField(srid=<srid d'origine>)

2021-11-25 16:34 UTC, submarcos commented on georiviere/river/models.py
> +        return Point(*result[0], srid=self.geom.srid)
geom_param_pos c'est pour sepcifier quels parametres sont des objets geometriques, pour les parser à la mode django (geos, geojson, ewkt acceptés)

2021-11-25 16:47 UTC, LePetitTim commented on georiviere/river/models.py
> +        return Point(*result[0], srid=self.geom.srid)
J'essaye

2021-11-26 08:36 UTC, submarcos commented on georiviere/river/functions.py
> +    geom_param_pos = (0, 1)
à mettre plutot dans https://github.com/Georiviere/Georiviere-admin/blob/master/georiviere/functions.py

2021-11-26 08:37 UTC, submarcos commented on georiviere/river/functions.py
> +    """ SQL Function class to get value from raster band (ST_VALUE) """
je ne pense pas que le commentaire soit adapté

2021-11-26 10:02 UTC, LePetitTim commented on georiviere/river/fields.py
>      It's a LineString field, with additional information about snapped vertices.
Changé

2021-11-26 10:02 UTC, LePetitTim commented on georiviere/river/fields.py
>              # geometry vertices
Changé

2021-11-26 15:01 UTC, submarcos approved these changes

2021-11-26 15:02 UTC, merged